# Generated by Django 4.0.5 on 2022-07-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderphotos_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderphotos',
            name='photo',
            field=models.URLField(),
        ),
    ]
