# Generated by Django 4.0.5 on 2022-06-23 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('executor', '0002_speciality_alter_executor_photo_executor_speciality'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutorComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_executor', to='executor.executor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_executor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'executor_comments',
                'ordering': ('created',),
            },
        ),
    ]
